version: "3.9"

services:
  svelte:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  api:
    build:
      context: ./api
    environment:
      PYTHONUNBUFFERED: "1"
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
